version: '3.8'
services:
  sender:
    build: ./container_a
    volumes:
      - ./container_a/app:/home/app
      - ./shared:/home/app/shared
      - ./data/to_send:/var/app/data/to_send
      - ./data/sent:/var/app/data/sent
      - ./data/sent_error:/var/app/data/sent_error
    env_file:
      - ./env/container_a.env
      - ./env/shared.env
  receiver:
    build: 
      context: ./container_b
      args: 
        - SERVER_PORT=5000
    volumes:
      - ./container_b/app:/home/app
      - ./shared:/home/app/shared
      - ./data/received:/var/app/data/received
      - ./data/received_error:/var/app/data/received_error
    env_file:
      - ./env/container_b.env
      - ./env/shared.env
