version: '3.8'
services:
  sender:
    build: ./container_a
    volumes:
      - ./container_a/app:/usr/src/app
      - ./shared:/usr/src/app/shared
      - ./data/to_send:/var/app/data/to_send
      - ./data/sent:/var/app/data/sent
      - ./data/sent_error:/var/app/data/sent_error
    env_file:
      - ./env/container_a.env
      - ./env/shared.env
    # command: 'bash'
    # stdin_open: true
    # tty: true
  receiver:
    build: ./container_b
    volumes:
      - ./container_b/app:/usr/src/app
      - ./shared:/usr/src/app/shared
      - ./data/received:/var/app/data/received
      - ./data/received_error:/var/app/data/received_error
    env_file:
      - ./env/container_b.env
      - ./env/shared.env
    # command: 'bash'
    # stdin_open: true
    # tty: true
    # depends_on:
    #   - sender
